enableEmoji: true
enableGitInfo: true
markup:
  goldmark:
    parser:
      attribute:
        block: true
params:
  title: "jan syring-lingenfelder .de"
  description: "Jan Syring-Lingenfelder - private Homepage - Software, Webdesign, IT"
menu:
  main:
    - identifier: itryarch
      name: I Try Arch (btw)
      url: /itryarch/
      weight: 1
    - identifier: selfhost
      name: Self Hosting
      url: /selfhost/
      weight: 1
    - identifier: ot
      name: Off Topic
      url: /ot/
      weight: 0
