enableEmoji: true
params:
  title: "jan syring-lingenfelder .de"
  description: "Jan Syring-Lingenfelder - private Homepage - Software, Webdesign, IT"
menu:
  main:
    - identifier: itryarch
      name: I Try Arch (btw)
      url: /itryarch/
    - identifier: ot
      name: Off Topic
      url: /ot/
